### ISSUE TITLE
Blackout_Curtains(Extra Utilities) nicht caftbar 

### ISSUE THREAD

**Issue by DirkSch** [BakermanLP/ProjectRETv8#10]
Wenn man die Wolle wie eine Tür ins craftingrid sollte Blackout_Curtains von Extrautilities herraus kommen. Leider kommen immer die Curtains von Malis Doors heraus. Ich brauche aber die  von Extra Utilities für dem Dark Room für die Pilzzucht in Agricraft.

**Comment by BakermanLP** [comment]
Workaround dazu:
eine der sechs Wolle Blöcke durch eine andere Wolle (Farbe ersetzen):
![blackcurtains](https://cloud.githubusercontent.com/assets/3873443/11710061/d3c57882-9f1c-11e5-9680-ad8d9bb10c6f.jpg)

**Comment by DirkSch** [comment]
Ok. Farben dürften ja kein Problem sein.
