### ISSUE TITLE
Railcraft Crusher vergisst das er ein Multiblock ist

### ISSUE THREAD

**Issue by DirkSch** [BakermanLP/ProjectRETv8#12]
Wenn man den Server stopt(auch SP) oder die Chunks entläd, weit weg wandert oder ander Dimension besucht, und dann zurück kommt ist der Rock Crusher kein Multiblock mehr. Ärgerlich wenn man gerade etwas verarbeitet. Durch neu setzen ploppen die Items herraus, aber es ist wieder ein Multiblock. Aber man muss es immer tun wenn man mal weiter weg war, sich ausloogt oder den Server gestopt hat.
Meiner Meinung nach ist Railcraft fehlerhaft.

**Comment by lordjoda** [comment]
Steht der Crusher über ne Chunk Grenze?

**Comment by DirkSch** [comment]
Es ist egal wo ich den hinstelle. Wenn er nicht im Betrieb, also nicht drin ist bleibt der ein Multiblock nach Serverneustart. Ist etwas drin während der Server neu startet vergisste er die Multiblockfähigkeit. Es scheint auch ein Server Only Problem zu sein im Singleplayer ist alles OK.

**Comment by BakermanLP** [comment]
Trotz mehrfachem Neustarts des Server scheint der Rock Crusher aus Railcraft seinen Multiblock bei uns nicht zu verlieren.
