### ISSUE TITLE
[Twilight Forest] Zu viele AOBD Oreberry Bushes

### ISSUE THREAD

**Issue by DerOliDE** [BakermanLP/ProjectRETv8#17]
Im Twilight Forest werden extrem viele AOBD Oreberry Bushes generiert und nicht nur die 0815 Teile, sondern alles bis hin zu Draconium.

**Comment by BakermanLP** [comment]
Leider nicht konfigurierbar, weder in TwilightForest.cfg noch in aobdbb.cfg . Nur generell einstellbar. Werde mal drüber schauen

**Comment by DerOliDE** [comment]
Schade, na dann machen wir das beste draus und besuchen bald mal den 
Twilight Forest. ^^

Am 16.12.2015 um 11:19 schrieb BakermanLP:

**Comment by BakermanLP** [comment]
Ich kann theoretisch und praktisch die "Gen chance" anpassen, bin mir aber nicht sicher auf was? Damit wird meines erachtens die Anzahl der Büsche bestimmt.  Aber interessanterweise sind in der Overworld und in Twilight Forest die gleichen Spawn Raten (kann nicht getrennt eingestellt werden). Wer da im Hintergrund wieder rumfummelt? Oder liegt das eventuell nur an den Max Y und Min Y Werten, da im Twilight Forest ja eine andere "Meereshöhe" eingestellt ist.

**Comment by DerOliDE** [comment]
Wäre eine Erklärung wenn es bspw heißt zwischen Höhe 0 und 64 spawnen 
wenn der Block Air ist, dann hat man underirisch in der Overworld 
natürlich weseltich weniger Büsche als oberirdisch im Twilight Forest.

Am 16.12.2015 um 11:26 schrieb BakermanLP:
