### ISSUE TITLE
Metallurgy Erze nicht im Extractor verarbeitbar

### ISSUE THREAD

**Issue by BakermanLP** [BakermanLP/ProjectRETv8#25]
Cross Ref: ganymedes01/Another-One-Bites-the-Dust#114

**Comment by BakermanLP** [comment]
Cross Ref: ReikaKalseki/Reika_Mods_Issues#516

**Comment by BakermanLP** [comment]
Danke an @lordjoda !

> I spent some time trying to find the issue of the problem @BakermanLP is describing and this is what I found:
> The ExtractAPI creates a new Instance of the CustomExtractLoader class. When The class RecipesExtractor (https://github.com/ReikaKalseki/RotaryCraft/blob/master/Auxiliary/RecipeManagers/RecipesExtractor.java#L71) is initialized it adds crafting recipes for all ores registered in the CustomExtractLoader. This is why NEI shows the recipes and the between products do work. But for the check if a ore can be processed or put in the extractor, the ReikaBlockHelper is called to check if the itemstack is an ore(https://github.com/ReikaKalseki/DragonAPI/blob/master/Libraries/World/ReikaBlockHelper.java#L132) but this check does NOT check if the ore is registered inside the CustomExtractLoader. 
> So I guess either the check has to be extended to include also the CustomExtractLoader or the loader has to also register the ores in one of the places that is checked if the item is a ore. 
> So in conclusion I would say that the ExtractAPI is not working. If you want I can also create a issue in the RotaryCraft issues.
> Hope that helps and I did not oversee something.

Wenn in der Datei https://github.com/ReikaKalseki/DragonAPI/blob/b9f9529ab22def034009e559c82fdcd65a193de6/ModRegistry/ModOreList.java#L40 die Erze nicht drinnen stehen, dann geht die Funktion isOre() nicht und damit nimmt der Extractor das Erz auch nicht an. Durch die ExtractAPI wird das Erz NICHT als isOre markiert oder in die Liste eingefügt.

Cross Ref: 
- ReikaKalseki/Reika_Mods_Issues#667
- ganymedes01/Another-One-Bites-the-Dust#72

**Comment by lordjoda** [comment]
Gerne ;)
