### ISSUE TITLE
RFTools connection timeouts

### ISSUE THREAD

**Issue by DerOliDE** [BakermanLP/ProjectRETv8#4]
RFTools macht noch immer massig Probleme beim einloggen, wenn man fastcraft clientseitig rauswirft funktioniert es "manchmal" aber auch nicht immer. Imho gehört RFTools raus geworfen solange sich daran nix ändert.

**Comment by BakermanLP** [comment]
Ich weiß nicht, ob es wirklich daran liegt. Mir fehlen hier Methoden um zu messen, was da wirklich passiert.

**Comment by DerOliDE** [comment]
Einfach mal zum testen deaktivieren und schauen ob es besser wird.

**Comment by BakermanLP** [comment]
Ich habe auch mal eine Anfrage bei Player im fastcraft Thread gemacht. 
http://forum.industrial-craft.net/index.php?page=Thread&postID=195278#post195278

Eventuell gibt es da ja irgendwas, was ich noch nicht kenne.

**Comment by DerOliDE** [comment]
Hoffentlich hat das dann mit unserem Starttermin hin, hab heut schon Butze und Joda gesehen wie sie online gekommen sind und gleich wieder offline gegangen worden sind. ^^

**Comment by BakermanLP** [comment]
Zu Dokumentations Zwecken hier noch der Post aus dem IC2 Forum:
[quote='Player','index.php?page=Thread&postID=195291#post195291']BakermanLP: I've updated the trigger feature to allow capturing logins, see version 1.50 and "/sampler trigger login". It'll capture every login, but the first number in the filename has the spike length in ms, so you should eventually see a problematic one. I'd like to have a look at the nps file if you manage to obtain a sample for a long pause.[/quote]

I've tried the new sampler version. Here are my results:
- Server timing after client has started: 673 ms ( File: [url]http://projectret.de/files/login-673-23191181704.nps[/url] )
- Server timing at next login: 23ms ( File: [url]http://projectret.de/files/login-23-23191583546.nps[/url] )

Client (via log messages);
- Client timing after client has started: 08:33:10 to 08:33:56 = 46 sec
- Client timing at next login: 08:40:03 to 08:40:22 = 19 sec

My results so far:
- Server timing doesn't seem to be a problem
- Client timing seems to be a problem, but this isn't mesureable in any way, or?

Additional information:
- Modpack: [url]https://github.com/BakermanLP/ProjectRETv8[/url]
- Forge 1492

Logfiles (Client):
- First login after clean restart of client: [url]http://pastebin.com/wLra7LWE[/url]
- Client Log next login (no client restart): [url]http://pastebin.com/H52WY6n6[/url]

**Comment by BakermanLP** [comment]
Im Moment scheint es zu funktionieren, zumindest, wenn die Welt bereits generiert ist. Teilweise ein Problem mit ATG und den Flüssen
